### ISSUE TITLE
A second push keeps the old URL title pushed before

### ISSUE THREAD

**Issue by rodrigoribeiro** [FancyPixel/pushbullet-safari#3]
Scenario:

1 - Safari have 2 tabs with different links opened;
2 - User access the first tab and press pushbullet button. Title and push URL are ok.
3 - User access the second tab and press pushbullet button.

Undesired result:

The URL title pushed is equals to first tab, not second. The correct would be change the URL and URL title for every push.

I'm using:

OS X Yosemite - 10.10.1
Safari - Version 8.0.2 (10600.2.5)

**Comment by andreamazz** [comment]
Hi @rodrigoribeiro 
Nice catch, you'll find a fix in commit 949c633. 
Thank you for your feedback! 

Cheers :beers:

**Comment by rodrigoribeiro** [comment]
Thank you so much for attention!

Will be the safari extension updated soon?

**Comment by andreamazz** [comment]
Sure you should already find version `1.0.1` live.
